// ===----------------------------------------------------------------------===//
//
// This source file is part of the swift-manifests open source project
//
// Copyright (c) 2026 Coen ten Thije Boonkkamp and the swift-manifests project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// ===----------------------------------------------------------------------===//

import SPM_Standard
import Testing

@testable import Manifest_Executable

extension Manifest.Executable {
    @Suite struct Test {
        @Suite struct `Relative Prefix` {}
        @Suite struct `Resolve` {}
        @Suite struct `Render Package Swift` {}
    }
}

// MARK: - relativePrefix

extension Manifest.Executable.Test.`Relative Prefix` {
    @Test
    func `descendant evalRoot returns one dotdot per extra segment`() throws {
        let consumer: File.Path = try File.Path("/tmp/swift-foo")
        let eval: File.Path = try File.Path("/tmp/swift-foo/.swift-lint/eval")
        let prefix = Manifest.Executable.Materializer.relativePrefix(from: eval, to: consumer)
        #expect(prefix == "../..")
    }

    @Test
    func `single-segment descendant returns single dotdot`() throws {
        let consumer: File.Path = try File.Path("/tmp/swift-foo")
        let eval: File.Path = try File.Path("/tmp/swift-foo/.swift-cache")
        let prefix = Manifest.Executable.Materializer.relativePrefix(from: eval, to: consumer)
        #expect(prefix == "..")
    }

    @Test
    func `non-descendant evalRoot returns dot defensively`() throws {
        let consumer: File.Path = try File.Path("/tmp/swift-foo")
        let eval: File.Path = try File.Path("/tmp/swift-bar/eval")
        let prefix = Manifest.Executable.Materializer.relativePrefix(from: eval, to: consumer)
        #expect(prefix == ".")
    }

    @Test
    func `equal paths return dot`() throws {
        let consumer: File.Path = try File.Path("/tmp/swift-foo")
        let eval: File.Path = try File.Path("/tmp/swift-foo")
        let prefix = Manifest.Executable.Materializer.relativePrefix(from: eval, to: consumer)
        #expect(prefix == ".")
    }
}

// MARK: - resolve

extension Manifest.Executable.Test.Resolve {
    @Test
    func `dot self-reference returns root prefix verbatim`() throws {
        let result: Swift.String = try Manifest.Executable.Materializer.resolve(
            ".",
            relativeTo: "../.."
        )
        #expect(result == "../..")
    }

    @Test
    func `empty self-reference returns root prefix verbatim`() throws {
        let result: Swift.String = try Manifest.Executable.Materializer.resolve(
            "",
            relativeTo: "../.."
        )
        #expect(result == "../..")
    }

    @Test
    func `relative consumer path joins under root prefix`() throws {
        let result: Swift.String = try Manifest.Executable.Materializer.resolve(
            "../../swift-foo",
            relativeTo: "../.."
        )
        #expect(result == "../../../../swift-foo")
    }
}

// MARK: - renderPackageSwift

extension Manifest.Executable.Test.`Render Package Swift` {
    @Test
    func `minimal Configuration emits well-formed Package_swift`() throws {
        let configuration = try Self.makeFixtureConfiguration()
        let rendered: Swift.String = try Manifest.Executable.Materializer.renderPackageSwift(
            configuration: configuration
        )

        #expect(rendered.contains("// swift-tools-version: 6.4"))
        #expect(rendered.contains("// AUTO-GENERATED by swift-manifests. DO NOT EDIT."))
        #expect(rendered.contains("import PackageDescription"))
        #expect(rendered.contains("name: \"Lint\","))
        #expect(rendered.contains(".macOS(.v27),"))
        #expect(rendered.contains(".executable(name: \"Lint\", targets: [\"Lint\"]),"))
        #expect(rendered.contains("swiftLanguageModes: [.v6]"))
    }

    @Test
    func `path-form dep is rewritten with consumer-to-eval prefix`() throws {
        let configuration = try Self.makeFixtureConfiguration()
        let rendered: Swift.String = try Manifest.Executable.Materializer.renderPackageSwift(
            configuration: configuration
        )
        // Consumer-supplied `"../../swift-primitives-linter-rules"` with
        // eval-relative-to-consumer prefix `"../.."` resolves to
        // `"../../../../swift-primitives-linter-rules"` from the eval
        // Package.swift's vantage.
        #expect(rendered.contains(".package(path: \"../../../../swift-primitives-linter-rules\")"))
    }

    @Test
    func `url-from dep emits unchanged`() throws {
        let configuration = Manifest.Executable.Configuration(
            consumerPackageRoot: try File.Path("/tmp/swift-foo"),
            consumerSourcePath: try File.Path("/tmp/swift-foo/Lint.swift"),
            evalRoot: try File.Path("/tmp/swift-foo/.swift-lint/eval"),
            executableName: "Lint",
            dependencies: [
                Package.Dependency(
                    source: .url(
                        "https://github.com/apple/swift-argument-parser.git",
                        from: "1.5.0"
                    ),
                    name: "swift-argument-parser",
                    products: ["ArgumentParser"]
                )
            ],
            platforms: [".macOS(.v27)"],
            swiftLanguageModes: [".v6"],
            toolsVersion: "6.3.1"
        )
        let rendered: Swift.String = try Manifest.Executable.Materializer.renderPackageSwift(
            configuration: configuration
        )
        #expect(
            rendered.contains(
                ".package(url: \"https://github.com/apple/swift-argument-parser.git\", from: \"1.5.0\")"
            )
        )
    }

    @Test
    func `url-range dep emits half-open range form`() throws {
        let configuration = Manifest.Executable.Configuration(
            consumerPackageRoot: try File.Path("/tmp/swift-foo"),
            consumerSourcePath: try File.Path("/tmp/swift-foo/Lint.swift"),
            evalRoot: try File.Path("/tmp/swift-foo/.swift-lint/eval"),
            executableName: "Lint",
            dependencies: [
                Package.Dependency(
                    source: .url(
                        "https://github.com/swiftlang/swift-syntax.git",
                        "602.0.0"..<"603.0.0"
                    ),
                    name: "swift-syntax",
                    products: ["SwiftSyntax"]
                )
            ],
            platforms: [".macOS(.v27)"],
            swiftLanguageModes: [".v6"],
            toolsVersion: "6.3.1"
        )
        let rendered: Swift.String = try Manifest.Executable.Materializer.renderPackageSwift(
            configuration: configuration
        )
        #expect(
            rendered.contains(
                ".package(url: \"https://github.com/swiftlang/swift-syntax.git\", \"602.0.0\"..<\"603.0.0\")"
            )
        )
    }

    @Test
    func `ecosystemSettings nil omits trailing for-loop`() throws {
        let configuration = Manifest.Executable.Configuration(
            consumerPackageRoot: try File.Path("/tmp/swift-foo"),
            consumerSourcePath: try File.Path("/tmp/swift-foo/Lint.swift"),
            evalRoot: try File.Path("/tmp/swift-foo/.swift-lint/eval"),
            executableName: "Lint",
            dependencies: [],
            platforms: [".macOS(.v27)"],
            swiftLanguageModes: [".v6"],
            ecosystemSettings: nil,
            toolsVersion: "6.3.1"
        )
        let rendered: Swift.String = try Manifest.Executable.Materializer.renderPackageSwift(
            configuration: configuration
        )
        #expect(!rendered.contains("for target in package.targets"))
    }

    @Test
    func `ecosystemSettings non-empty emits trailing for-loop with settings`() throws {
        let configuration = Manifest.Executable.Configuration(
            consumerPackageRoot: try File.Path("/tmp/swift-foo"),
            consumerSourcePath: try File.Path("/tmp/swift-foo/Lint.swift"),
            evalRoot: try File.Path("/tmp/swift-foo/.swift-lint/eval"),
            executableName: "Lint",
            dependencies: [],
            platforms: [".macOS(.v27)"],
            swiftLanguageModes: [".v6"],
            ecosystemSettings: [
                ".enableUpcomingFeature(\"ExistentialAny\")",
                ".enableUpcomingFeature(\"MemberImportVisibility\")",
            ],
            toolsVersion: "6.3.1"
        )
        let rendered: Swift.String = try Manifest.Executable.Materializer.renderPackageSwift(
            configuration: configuration
        )
        #expect(
            rendered.contains(
                "for target in package.targets where ![.system, .binary, .plugin, .macro].contains(target.type) {"
            )
        )
        #expect(rendered.contains(".enableUpcomingFeature(\"ExistentialAny\"),"))
        #expect(rendered.contains(".enableUpcomingFeature(\"MemberImportVisibility\"),"))
        #expect(
            rendered.contains("target.swiftSettings = (target.swiftSettings ?? []) + ecosystem")
        )
    }
}

extension Manifest.Executable.Test.`Render Package Swift` {
    /// Lint-shaped fixture Configuration: consumer at `/tmp/swift-foo`,
    /// eval at `/tmp/swift-foo/.swift-lint/eval`, one path-form dep
    /// matching the consumer-side `"../../swift-primitives-linter-rules"`
    /// shape commonly found in Lint.swift dispatches.
    fileprivate static func makeFixtureConfiguration() throws -> Manifest.Executable.Configuration {
        Manifest.Executable.Configuration(
            consumerPackageRoot: try File.Path("/tmp/swift-foo"),
            consumerSourcePath: try File.Path("/tmp/swift-foo/Lint.swift"),
            evalRoot: try File.Path("/tmp/swift-foo/.swift-lint/eval"),
            executableName: "Lint",
            dependencies: [
                Package.Dependency(
                    source: .path("../../swift-primitives-linter-rules"),
                    name: "swift-primitives-linter-rules",
                    products: ["Linter Primitives Rules"]
                )
            ],
            platforms: [".macOS(.v27)"],
            swiftLanguageModes: [".v6"],
            ecosystemSettings: [".enableUpcomingFeature(\"ExistentialAny\")"],
            toolsVersion: "6.3.1"
        )
    }
}
