// ===----------------------------------------------------------------------===//
//
// This source file is part of the swift-manifests open source project
//
// Copyright (c) 2026 Coen ten Thije Boonkkamp and the swift-manifests project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// ===----------------------------------------------------------------------===//

internal import File_System
public import Manifest_Primitives
internal import Package_Primitives

extension Manifest.Executable {
    /// Renders the eval project (`Package.swift` + `Sources/<executableName>/main.swift`)
    /// for a consumer-manifest dispatch.
    ///
    /// Always overwrites; the eval project is fully derived from the
    /// supplied ``Configuration`` plus the consumer's source bytes,
    /// so re-rendering is idempotent.
    public enum Materializer {}
}

extension Manifest.Executable.Materializer {
    /// Materialize the eval project on disk.
    ///
    /// Layout:
    /// ```
    /// <evalRoot>/
    ///   Package.swift
    ///   Sources/
    ///     <executableName>/
    ///       main.swift
    /// ```
    ///
    /// `main.swift` is a verbatim copy of
    /// ``Manifest/Executable/Configuration/consumerSourcePath``;
    /// `Package.swift` is rendered from the Configuration.
    @usableFromInline
    internal static func materialize(
        configuration: Manifest.Executable.Configuration
    ) throws(Manifest.Executable.Error) {
        let sourcesParentDirectory: File.Path = configuration.evalRoot / "Sources"
        let executableSourceDirectory: File.Path
        do throws(Paths.Path.Component.Error) {
            executableSourceDirectory = try sourcesParentDirectory.appending(configuration.executableName)
        } catch {
            throw .materializationFailed(
                reason: "invalid executable name `\(configuration.executableName)`: \(error)"
            )
        }
        let packageSwiftPath: File.Path = configuration.evalRoot / "Package.swift"
        let mainSwiftPath: File.Path = executableSourceDirectory / "main.swift"

        try Self.createDirectoryRecursive(at: executableSourceDirectory)

        let packageSwift: Swift.String = try Self.renderPackageSwift(configuration: configuration)
        try Self.writeAtomic(packageSwift, to: packageSwiftPath)

        let consumerSource: Swift.String = try Self.readFile(at: configuration.consumerSourcePath)
        try Self.writeAtomic(consumerSource, to: mainSwiftPath)
    }

    /// Render the eval project's `Package.swift` source.
    ///
    /// Output shape:
    /// 1. `// swift-tools-version: <toolsVersion>` directive
    /// 2. `import PackageDescription`
    /// 3. `let package = Package(...)` literal with `name`,
    ///    `platforms`, `products`, `dependencies`, `targets`, and
    ///    `swiftLanguageModes`
    /// 4. Optional trailing `for target in package.targets ...`
    ///    block applying ``Configuration/ecosystemSettings``
    @usableFromInline
    internal static func renderPackageSwift(
        configuration: Manifest.Executable.Configuration
    ) throws(Manifest.Executable.Error) -> Swift.String {
        let evalRelativeToConsumer: Swift.String = Self.relativePrefix(
            from: configuration.evalRoot,
            to: configuration.consumerPackageRoot
        )

        var lines: [Swift.String] = [
            "// swift-tools-version: \(configuration.toolsVersion)",
            "// AUTO-GENERATED by swift-manifests. DO NOT EDIT.",
            "// Source: \(configuration.consumerSourcePath.string)",
            "",
            "import PackageDescription",
            "",
            "let package = Package(",
            "    name: \"\(configuration.executableName)\","
        ]

        if configuration.platforms.isEmpty {
            lines.append("    platforms: [],")
        } else {
            lines.append("    platforms: [")
            for platform in configuration.platforms {
                lines.append("        \(platform),")
            }
            lines.append("    ],")
        }

        lines.append(contentsOf: [
            "    products: [",
            "        .executable(name: \"\(configuration.executableName)\", targets: [\"\(configuration.executableName)\"]),",
            "    ],",
            "    dependencies: ["
        ])

        for dep in configuration.dependencies {
            switch dep.source {
            case .path(let path):
                let resolvedPath: Swift.String = try Self.resolve(path, relativeTo: evalRelativeToConsumer)
                lines.append("        .package(path: \"\(resolvedPath)\"),")
            case .urlFrom(url: let url, from: let from):
                lines.append("        .package(url: \"\(url)\", from: \"\(from)\"),")
            case .urlRange(url: let url, lower: let lower, upper: let upper):
                lines.append("        .package(url: \"\(url)\", \"\(lower)\"..<\"\(upper)\"),")
            }
        }

        lines.append(contentsOf: [
            "    ],",
            "    targets: [",
            "        .executableTarget(",
            "            name: \"\(configuration.executableName)\",",
            "            dependencies: ["
        ])

        for dep in configuration.dependencies {
            for product in dep.products {
                lines.append("                .product(name: \"\(product)\", package: \"\(dep.name)\"),")
            }
        }

        lines.append(contentsOf: [
            "            ]",
            "        ),",
            "    ],"
        ])

        let modes: Swift.String = configuration.swiftLanguageModes.joined(separator: ", ")
        lines.append("    swiftLanguageModes: [\(modes)]")
        lines.append(")")
        lines.append("")

        if let ecosystem: [Swift.String] = configuration.ecosystemSettings, !ecosystem.isEmpty {
            lines.append("for target in package.targets where ![.system, .binary, .plugin, .macro].contains(target.type) {")
            lines.append("    let ecosystem: [SwiftSetting] = [")
            for setting in ecosystem {
                lines.append("        \(setting),")
            }
            lines.append("    ]")
            lines.append("    target.swiftSettings = (target.swiftSettings ?? []) + ecosystem")
            lines.append("}")
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    /// Compute the relative prefix (e.g., `"../.."`) from
    /// `evalRoot` up to `consumerPackageRoot`. Used to rewrite
    /// consumer-relative `.package(path:)` declarations so they
    /// resolve from the eval `Package.swift`'s vantage.
    ///
    /// Returns `"."` defensively when `evalRoot` is not a
    /// descendant of `consumerPackageRoot` — the eval
    /// `Package.swift` will fail to resolve `.package(path:)` deps
    /// in that case, surfacing the configuration error at build
    /// time.
    @usableFromInline
    internal static func relativePrefix(
        from evalRoot: File.Path,
        to consumerPackageRoot: File.Path
    ) -> Swift.String {
        guard let relative: File.Path = evalRoot.relative(to: consumerPackageRoot) else {
            return "."
        }
        if relative.string == "." {
            return "."
        }
        let depth: Swift.Int = relative.components.count
        if depth == 0 {
            return "."
        }
        return Swift.Array(repeating: "..", count: depth).joined(separator: "/")
    }

    /// Resolve a consumer-supplied path-form dep into a path
    /// relative to the eval `Package.swift`.
    ///
    /// `consumerPath` is the literal string the consumer wrote
    /// (e.g., `"../../swift-foo"`, `"."`, `""`); `root` is the
    /// pre-computed relative prefix from
    /// ``relativePrefix(from:to:)``. The result is the path string
    /// the eval `Package.swift` will use.
    ///
    /// Self-reference shortcuts: `"."` and the empty string both
    /// collapse to `root`, the consumer's own package root from the
    /// eval's vantage. Naive concatenation (`"../.." + "/" + "."`)
    /// would yield `"../../."` which SwiftPM's `.package(path:)`
    /// parser rejects with "unknown package '.'".
    @usableFromInline
    internal static func resolve(
        _ consumerPath: Swift.String,
        relativeTo root: Swift.String
    ) throws(Manifest.Executable.Error) -> Swift.String {
        if consumerPath.isEmpty || consumerPath == "." {
            return root
        }
        let consumer: File.Path
        let base: File.Path
        do throws(Paths.Path.Error) {
            consumer = try File.Path(consumerPath)
            base = try File.Path(root)
        } catch {
            throw .materializationFailed(
                reason: "invalid SwiftPM path-form dep `\(consumerPath)` (relative to `\(root)`): \(error)"
            )
        }
        return base.appending(consumer).string
    }

    fileprivate static func createDirectoryRecursive(
        at path: File.Path
    ) throws(Manifest.Executable.Error) {
        do throws(File.System.Create.Directory.Error) {
            try File.Directory(path).create.recursive()
        } catch {
            throw .materializationFailed(reason: "create directory \(path.string): \(error)")
        }
    }

    fileprivate static func writeAtomic(
        _ contents: Swift.String,
        to path: File.Path
    ) throws(Manifest.Executable.Error) {
        do throws(File.System.Write.Atomic.Error) {
            try File(path).write.atomic(contents)
        } catch {
            throw .materializationFailed(reason: "write \(path.string): \(error)")
        }
    }

    fileprivate static func readFile(
        at path: File.Path
    ) throws(Manifest.Executable.Error) -> Swift.String {
        let bytes: [Swift.UInt8]
        do throws(File.System.Read.Full.Error) {
            bytes = try File(path).read.full { (span: Span<Swift.UInt8>) -> [Swift.UInt8] in
                var array: [Swift.UInt8] = []
                array.reserveCapacity(span.count)
                for i in 0..<span.count {
                    array.append(span[i])
                }
                return array
            }
        } catch {
            throw .readFailed(path: path, description: "\(error)")
        }
        return Swift.String(decoding: bytes, as: UTF8.self)
    }
}
