internal import File_System
public import Manifest
internal import Package
internal import SPM_Standard

extension Manifest.Executable {

    public enum Materializer {}
}

extension Manifest.Executable.Materializer {

    @usableFromInline
    internal static func materialize(
        configuration: Manifest.Executable.Configuration
    ) throws(Manifest.Executable.Error) {
        let sourcesParentDirectory: File.Path = configuration.evalRoot / "Sources"
        let executableSourceDirectory: File.Path
        do throws(Paths.Path.Component.Error) {
            executableSourceDirectory = try sourcesParentDirectory.appending(
                configuration.executableName
            )
        } catch {
            throw .materializationFailed(
                reason: "invalid executable name `\(configuration.executableName)`: \(error)"
            )
        }
        let packageSwiftPath: File.Path = configuration.evalRoot / "Package.swift"
        let mainSwiftPath: File.Path = executableSourceDirectory / "main.swift"

        try Self.createDirectoryRecursive(at: executableSourceDirectory)

        let packageSwift: Swift.String = try Self.renderPackageSwift(configuration: configuration)
        try Self.writeAtomic(packageSwift, to: packageSwiftPath)

        let consumerSource: Swift.String = try Self.readFile(at: configuration.consumerSourcePath)
        try Self.writeAtomic(consumerSource, to: mainSwiftPath)
    }

    @usableFromInline
    internal static func renderPackageSwift(
        configuration: Manifest.Executable.Configuration
    ) throws(Manifest.Executable.Error) -> Swift.String {
        let evalRelativeToConsumer: Swift.String = Self.relativePrefix(
            from: configuration.evalRoot,
            to: configuration.consumerPackageRoot
        )

        var lines: [Swift.String] = [
            "// swift-tools-version: \(configuration.toolsVersion)",
            "// AUTO-GENERATED by swift-manifests. DO NOT EDIT.",
            "// Source: \(configuration.consumerSourcePath.string)",
            "",
            "import PackageDescription",
            "",
            "let package = Package(",
            "    name: \"\(configuration.executableName)\",",
        ]

        if configuration.platforms.isEmpty {
            lines.append("    platforms: [],")
        } else {
            lines.append("    platforms: [")
            for platform in configuration.platforms {
                lines.append("        \(platform),")
            }
            lines.append("    ],")
        }

        lines.append(contentsOf: [
            "    products: [",
            "        .executable(name: \"\(configuration.executableName)\", targets: [\"\(configuration.executableName)\"]),",
            "    ],",
            "    dependencies: [",
        ])

        for dep in configuration.dependencies {
            switch dep.source {
            case .path(let path):
                let resolvedPath: Swift.String = try Self.resolve(
                    path,
                    relativeTo: evalRelativeToConsumer
                )
                lines.append("        .package(path: \"\(resolvedPath)\"),")

            case .url(let url, let requirement):
                lines.append(Self.render(url: url.value, requirement: requirement))

            case .registry(let identity, let requirement):
                lines.append(Self.render(registry: identity, requirement: requirement))
            }
        }

        lines.append(contentsOf: [
            "    ],",
            "    targets: [",
            "        .executableTarget(",
            "            name: \"\(configuration.executableName)\",",
            "            dependencies: [",
        ])

        for dep in configuration.dependencies {
            for product in dep.products {
                lines.append(
                    "                .product(name: \"\(product)\", package: \"\(dep.name)\"),"
                )
            }
        }

        lines.append(contentsOf: [
            "            ]",
            "        ),",
            "    ],",
        ])

        let modes: Swift.String = configuration.swiftLanguageModes.joined(separator: ", ")
        lines.append("    swiftLanguageModes: [\(modes)]")
        lines.append(")")
        lines.append("")

        if let ecosystem: [Swift.String] = configuration.ecosystemSettings, !ecosystem.isEmpty {
            lines.append(
                "for target in package.targets where ![.system, .binary, .plugin, .macro].contains(target.type) {"
            )
            lines.append("    let ecosystem: [SwiftSetting] = [")
            for setting in ecosystem {
                lines.append("        \(setting),")
            }
            lines.append("    ]")
            lines.append("    target.swiftSettings = (target.swiftSettings ?? []) + ecosystem")
            lines.append("}")
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    fileprivate static func render(
        url: Swift.String,
        requirement: Package.Requirement
    ) -> Swift.String {
        switch requirement {
        case .from(let version):
            return "        .package(url: \"\(url)\", from: \"\(version)\"),"

        case .upToNextMajor(from: let version):
            return "        .package(url: \"\(url)\", .upToNextMajor(from: \"\(version)\")),"

        case .upToNextMinor(from: let version):
            return "        .package(url: \"\(url)\", .upToNextMinor(from: \"\(version)\")),"

        case .range(let range):
            return "        .package(url: \"\(url)\", \(Self.rangeLiteral(range))),"

        case .exact(let version):
            return "        .package(url: \"\(url)\", exact: \"\(version)\"),"

        case .branch(let branch):
            return "        .package(url: \"\(url)\", branch: \"\(branch)\"),"

        case .revision(let revision):
            return "        .package(url: \"\(url)\", revision: \"\(revision)\"),"
        }
    }

    fileprivate static func render(
        registry identity: Package.Identity,
        requirement: Package.Requirement
    ) -> Swift.String {
        let id: Swift.String = "\(identity.scope).\(identity.name)"
        switch requirement {
        case .from(let version):
            return "        .package(id: \"\(id)\", from: \"\(version)\"),"

        case .upToNextMajor(from: let version):
            return "        .package(id: \"\(id)\", .upToNextMajor(from: \"\(version)\")),"

        case .upToNextMinor(from: let version):
            return "        .package(id: \"\(id)\", .upToNextMinor(from: \"\(version)\")),"

        case .range(let range):
            return "        .package(id: \"\(id)\", \(Self.rangeLiteral(range))),"

        case .exact(let version):
            return "        .package(id: \"\(id)\", exact: \"\(version)\"),"

        case .branch, .revision:

            return "        // ERROR: registry deps do not support branch/revision: \(id)"
        }
    }

    fileprivate static func rangeLiteral(
        _ range: Version.Range<Version.Semantic>
    ) -> Swift.String {
        guard case .inclusive(let lower) = range.lowerBound,
            case .exclusive(let upper) = range.upperBound
        else {
            return "/* ERROR: range deps require .inclusive lower / .exclusive upper */"
        }
        return "\"\(lower)\"..<\"\(upper)\""
    }

    @usableFromInline
    internal static func relativePrefix(
        from evalRoot: File.Path,
        to consumerPackageRoot: File.Path
    ) -> Swift.String {
        guard let relative: File.Path = evalRoot.relative(to: consumerPackageRoot) else {
            return "."
        }
        if relative.string == "." {
            return "."
        }
        let depth: Swift.Int = relative.components.count
        if depth == 0 {
            return "."
        }
        return Swift.Array(repeating: "..", count: depth).joined(separator: "/")
    }

    @usableFromInline
    internal static func resolve(
        _ consumerPath: Swift.String,
        relativeTo root: Swift.String
    ) throws(Manifest.Executable.Error) -> Swift.String {
        if consumerPath.isEmpty || consumerPath == "." {
            return root
        }
        let consumer: File.Path
        let base: File.Path
        do throws(Paths.Path.Error) {
            consumer = try File.Path(consumerPath)
            base = try File.Path(root)
        } catch {
            throw .materializationFailed(
                reason:
                    "invalid SwiftPM path-form dep `\(consumerPath)` (relative to `\(root)`): \(error)"
            )
        }
        let joined: Swift.String = base.appending(consumer).string
        #if os(Windows)

            return Swift.String(joined.map { $0 == "\\" ? "/" : $0 })
        #else
            return joined
        #endif
    }

    fileprivate static func createDirectoryRecursive(
        at path: File.Path
    ) throws(Manifest.Executable.Error) {
        do throws(File.System.Create.Directory.Error) {
            try File.Directory(path).create.recursive()
        } catch {
            throw .materializationFailed(reason: "create directory \(path.string): \(error)")
        }
    }

    fileprivate static func writeAtomic(
        _ contents: Swift.String,
        to path: File.Path
    ) throws(Manifest.Executable.Error) {
        do throws(File.System.Write.Atomic.Error) {
            try File(path).write.atomic(contents)
        } catch {
            throw .materializationFailed(reason: "write \(path.string): \(error)")
        }
    }

    fileprivate static func readFile(
        at path: File.Path
    ) throws(Manifest.Executable.Error) -> Swift.String {
        let bytes: [Byte]
        do throws(Either<File.System.Read.Full.Error, Never>) {
            bytes = try File(path).read.full { (span: Swift.Span<Byte>) -> [Byte] in
                var array: [Byte] = []
                array.reserveCapacity(span.count)
                for i in 0..<span.count {
                    array.append(span[i])
                }
                return array
            }
        } catch {
            throw .readFailed(path: path, description: "\(error.value)")
        }
        return Swift.String(decoding: bytes, as: UTF8.self)
    }
}
